import = ["~/.dotfiles/.config/alacritty/dracula.toml"]

[font]
  normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
  bold = { style = "Bold" }
  italic = { style = "Italic" }
  size = 16.0  # Adjust the size as needed

